---
- hosts: localhost
  become: true
  tasks:
          - name: create build
            docker_image: 
                name=testt
                tag=v1
                path=/home/ubuntu/ansible-docker/docker/
                state=present
          - name: create container
            docker_container:
                 name: testtcon
                 image: testt:v1
                 command: sleep infinity
                 state: present
